# Port that the proxy server should listen on. The default is 8888.
port: 8888

# Set to true to verify signatures. This should always be set to true. Disabling
# it means requests sent from non-Amazon parties will be forwarded.
verifySignatures: true

# Set to true to verify timestamps. This should be set to true to avoid replay
# attacks.
verifyTimestamps: true

# A list of applications that alexa_dispatcher should handle. When
# alexa_dispatcher gets a request from Amazon, it decides which application to
# route its request to by looking at this list.
applications:
  - endpoint: http://localhost:1234
    applicationId: MyApplicationId-XXXX-XX-XX
  - endpoint: http://localhost:1235
    applicationId: MyApplicationId-YYYY-YY-YY
